---
extends: default

rules:
  line-length:
    max: 150
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
  trailing-spaces: enable
  empty-lines:
    max: 1
    max-start: 1
    max-end: 1
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
    check-keys: false
